In [ ]:
import numpy as np
import pandas as pd
import time
from statistics import stdev

In [ ]:
!wget "http://files.grouplens.org/datasets/movielens/ml-1m.zip"
!unzip ml-1m.zip
!ls
!ls ml-1m/
df = pd.read_csv('ml-1m/ratings.dat', delimiter='::', header=None, names=['user_emb_id', 'movie_emb_id', 'rating', 'timestamp'], usecols=['user_emb_id', 'movie_emb_id', 'rating'], engine='python')

len(df.user_emb_id.unique()), len(df.movie_emb_id.unique())
num_users = df['user_emb_id'].unique().max() + 1
num_movies = df['movie_emb_id'].unique().max() + 1
Rating = df.pivot( index = 'user_emb_id', columns ='movie_emb_id',values = 'rating').fillna(0)
print(Rating.shape)

--2021-08-22 08:18:06--  http://files.grouplens.org/datasets/movielens/ml-1m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5917549 (5.6M) [application/zip]
Saving to: ‘ml-1m.zip’

ml-1m.zip           100%[===================>]   5.64M  4.12MB/s    in 1.4s    

2021-08-22 08:18:08 (4.12 MB/s) - ‘ml-1m.zip’ saved [5917549/5917549]

Archive:  ml-1m.zip
   creating: ml-1m/
  inflating: ml-1m/movies.dat        
  inflating: ml-1m/ratings.dat       
  inflating: ml-1m/README            
  inflating: ml-1m/users.dat         
ml-1m  ml-1m.zip  sample_data
movies.dat  ratings.dat  README  users.dat
(6040, 3706)


In [ ]:
!wget "http://files.grouplens.org/datasets/movielens/ml-100k.zip"
!unzip ml-100k.zip
!ls
!ls ml-100k/
df = pd.read_csv("ml-100k/u.data",sep='\t',names="user_emb_id,movie_emb_id,rating,timestamp".split(","))

--2021-08-22 08:18:19--  http://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4924029 (4.7M) [application/zip]
Saving to: ‘ml-100k.zip’

ml-100k.zip         100%[===================>]   4.70M  3.44MB/s    in 1.4s    

2021-08-22 08:18:21 (3.44 MB/s) - ‘ml-100k.zip’ saved [4924029/4924029]

Archive:  ml-100k.zip
   creating: ml-100k/
  inflating: ml-100k/allbut.pl       
  inflating: ml-100k/mku.sh          
  inflating: ml-100k/README          
  inflating: ml-100k/u.data          
  inflating: ml-100k/u.genre         
  inflating: ml-100k/u.info          
  inflating: ml-100k/u.item          
  inflating: ml-100k/u.occupation    
  inflating: ml-100k/u.user          
  inflating: ml-100k/u1.base         
  inflating: ml-100k/u1.test         
  inflating: ml-100k/u2.base

In [ ]:





print(df)
len(df.user_emb_id.unique()), len(df.movie_emb_id.unique())
num_users = df['user_emb_id'].unique().max() + 1
num_movies = df['movie_emb_id'].unique().max() + 1
Rating = df.pivot( index = 'user_emb_id', columns ='movie_emb_id',values = 'rating').fillna(0)
print(Rating.shape)

       user_emb_id  movie_emb_id  rating  timestamp
0              196           242       3  881250949
1              186           302       3  891717742
2               22           377       1  878887116
3              244            51       2  880606923
4              166           346       1  886397596
...            ...           ...     ...        ...
99995          880           476       3  880175444
99996          716           204       5  879795543
99997          276          1090       1  874795795
99998           13           225       2  882399156
99999           12           203       3  879959583

[100000 rows x 4 columns]
(943, 1682)


In [ ]:
Rating=np.array(Rating)

In [ ]:
print(np.count_nonzero(Rating))

100000


In [ ]:
count=[]
for i  in range(Rating.shape[1]):
  count.append(np.count_nonzero(Rating[:,i]))
    

In [ ]:
print(np.max(count))

583


In [ ]:
cold=[]
for i  in range(Rating.shape[1]):
  if(np.count_nonzero(Rating[:,i])<15):
    #print(i,np.nonzero(Rating[:,i]))
    cold.append(Rating[:,i])
cold=np.array(cold)

In [ ]:
print(len(cold))

650


In [ ]:
contro_item=[]
for i  in range(Rating.shape[1]):
  if(stdev(Rating[:,i])>1.5):
    #print(i,np.nonzero(Rating[:,i]))
    contro_item.append(Rating[:,i])
contro_item=np.array(contro_item)

print(contro_item.shape)

(143, 943)


In [ ]:
heavy_item=[]
for i  in range(Rating.shape[1]):
  if(np.count_nonzero(Rating[:,i])>100):
    #print(i,np.nonzero(Rating[:,i]))
    heavy_item.append(Rating[:,i])
heavy_item=np.array(heavy_item)

print(heavy_item.shape)

(334, 943)


In [ ]:
cold=np.array(cold)

In [ ]:
print(cold.shape)

(650, 943)


In [ ]:
n= np.count_nonzero(heavy_item)
print(n)

64419


In [ ]:
print(max(2,0.01))

2


In [ ]:
print((Rating[3520][140]))

IndexError: ignored

In [ ]:
for i in range(len(Rating)):
  for j in range (len(Rating[i])):
   if Rating[i][j]==5 :
     print(Rating[i][j])

Streaming output truncated to the last 5000 lines.
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5

In [ ]:

import numpy
import sys 
import math
 
class MF_Theta(object):
    
 
    def __init__(self):
        self.Q = None
        self.P = None
        
 
    def fit(self,user_x_product,theta, sim_graph,count,latent_features_guess=32, learning_rate=0.01, steps=20, regularization_penalty=0.1,gamma=0.01, convergeance_threshold=0.001):
     
        print ('training model...')
        return self.__factor_matrix(user_x_product,theta,sim_graph,count, latent_features_guess, learning_rate, steps, regularization_penalty,gamma, convergeance_threshold)
 
    def predict_instance(self, row_index):
       
        return numpy.dot(self.P[row_index, :], self.Q.T)
 
    def predict_all(self):
       
        return numpy.dot(self.P, self.Q.T)
   
    def get_models(self):
       
         return self.P, self.Q


    def sim(self,q1,q2,R):

      sum=0     
      s1=0
      s2=0   
      for i in range (len(R)):         
        if ( R[i][q1]>0) and (R[i][q2]>0):
          a=R[i][q1]- np.mean(R[:,q1])
          b=R[i][q2]- np.mean(R[:,q2])
          sum+= a * b
          a2=pow(a,2)
          b2=pow(b,2)
          s1+=a2
          s2+=b2
      #    print(i,a2,b2,s1,s2)
      if np.sqrt(s1)*np.sqrt(s2)>0:
        return(sum/(np.sqrt(s1)*np.sqrt(s2)))
      else:
        return 0
 
    def __factor_matrix(self, R,theta,S, count,K, alpha, steps, beta,gamma, error_limit):
        
        # Transform regular array to numpy array
        R = np.array(R)
 
        # Generate P - N x K
        # Use random values to start. Best performance
        N = len(R)
        M = len(R[0])
        P = numpy.random.rand(N, K)
 
        # Generate Q - M x K
        # Use random values to start. Best performance
        #Q=theta
        Q = numpy.random.rand(M, K)
        Q = Q.T
        error = 0
        # iterate through max # of steps
        for step in range(steps):
 
            # iterate each cell in r
            for i in range (len(R)):
                for j in range (len(R[i])):
                    if R[i][j] > 0:                   
                        # get the eij (error) side of the equation
                        eij = R[i][j] - numpy.dot(P[i, :], Q[:, j])
                        #print(numpy.dot(P[i, :], Q[:, j]),R[i][j]) 
                        for k in range(K):
                            # (*update_rule) update pik_hat
                            P[i][k] = P[i][k] + alpha * ( 2 *eij * Q[k][j]-beta * P[i][k]) 
                            sum=0
                            
                            for l in range(3):#len(S[j])):
                              q2=S[j][l]                            
                              print(q2,i,j,k)
                              sum+=  (Q[k][j]-Q[k][q2])
 
                            
                            ga=5/(count[i])
                           # print(ga)
                            Q[k][j] = Q[k][j] + alpha * ( 2 * eij * P[i][k] - beta * Q[k][j]-ga* sum )
                            #print('after Q[k][j]=',Q[k][j])
                            #print(' Q[k][q2]]=',Q[k][q2])
                           # Q[k][j] = Q[k][j] + alpha * (  2 *eij * P[i][k]- beta * (Q[k][j])-theta[k][j] ))
                           # print(Q[k][j],"  ",theta[k][j],"  ", Q[k][j]-theta[k][j])
          
        self.Q = Q.T
        self.P = P
 
    def rmse(self,R):
        """
        A function to compute the total mean square error
        """
        xs, ys = R.nonzero()
        predicted = self.predict_all()
        count=0
        error = 0
        for x, y in zip(xs, ys):
            count=count+1
            error += pow((R[x, y] - predicted[x, y]), 2)
        return np.sqrt(error/count)
   
    
    def mae(self,R):
 
      xs, ys = R.nonzero()
      predicted = self.predict_all()
      count=0
      error = 0
      for x, y in zip(xs, ys):
 
        count=count+1
        error += abs((R[x, y] - predicted[x, y]))
      return (error/count)
    

In [ ]:

import numpy
import sys 
 
class MF(object):
    
 
    def __init__(self):
        self.Q = None
        self.P = None
        
 
    def fit(self,user_x_product,latent_features_guess=32, learning_rate=0.01, steps=20, regularization_penalty=0.1, convergeance_threshold=0.001):
     
        print ('training model...')
        return self.__factor_matrix(user_x_product, latent_features_guess, learning_rate, steps, regularization_penalty, convergeance_threshold)
 
    def predict_instance(self, row_index):
       
        return numpy.dot(self.P[row_index, :], self.Q.T)
 
    def predict_all(self):
       
        return numpy.dot(self.P, self.Q.T)
   
    def get_models(self):
       
         return self.P, self.Q


 
    def __factor_matrix(self, R, K, alpha, steps, beta, error_limit):
        
        # Transform regular array to numpy array
        R = np.array(R)
 
        # Generate P - N x K
        # Use random values to start. Best performance
        N = len(R)
        M = len(R[0])
        P = numpy.random.rand(N, K)
 
        # Generate Q - M x K
        # Use random values to start. Best performance
        #Q=theta
        Q = numpy.random.rand(M, K)
        Q = Q.T
        error = 0
        # iterate through max # of steps
        for step in range(steps): 
            # iterate each cell in r
            for i in range (len(R)):
                for j in range (len(R[i])):
                    if R[i][j] > 0:                                       
                        eij = R[i][j] - numpy.dot(P[i, :], Q[:, j])                      
                        for k in range(K):                         
                            P[i][k] = P[i][k] + alpha * ( 2 *eij * Q[k][j]-beta * P[i][k])                                                       
                            Q[k][j] = Q[k][j] + alpha * ( 2 * eij * P[i][k] - beta * Q[k][j])                           
        self.Q = Q.T
        self.P = P
 
    def rmse(self,R):
      
        xs, ys = R.nonzero()
        predicted = self.predict_all()
        count=0
        error = 0
        for x, y in zip(xs, ys):
            count=count+1
            error += pow((R[x, y] - predicted[x, y]), 2)
        return np.sqrt(error/count)
   
    
    def mae(self,R):
 
      xs, ys = R.nonzero()
      predicted = self.predict_all()
      count=0
      error = 0
      for x, y in zip(xs, ys):
 
        count=count+1
        error += abs((R[x, y] - predicted[x, y]))
      return (error/count)
    

In [ ]:

import numpy
import sys 
import math
 
class MF_Theta_1M(object):
    
 
    def __init__(self):
        self.Q = None
        self.P = None
        
 
    def fit(self,user_x_product,theta, sim_graph,count,latent_features_guess=32, learning_rate=0.01, steps=20, regularization_penalty=0.1,gamma=0.01, convergeance_threshold=0.001):
     
        print ('training model...')
        return self.__factor_matrix(user_x_product,theta,sim_graph,count, latent_features_guess, learning_rate, steps, regularization_penalty,gamma, convergeance_threshold)
 
    def predict_instance(self, row_index):
       
        return numpy.dot(self.P[row_index, :], self.Q.T)
 
    def predict_all(self):
       
        return numpy.dot(self.P, self.Q.T)
   
    def get_models(self):
       
         return self.P, self.Q


    def sim(self,q1,q2,R):

      sum=0     
      s1=0
      s2=0   
      for i in range (len(R)):         
        if ( R[i][q1]>0) and (R[i][q2]>0):
          a=R[i][q1]- np.mean(R[:,q1])
          b=R[i][q2]- np.mean(R[:,q2])
          sum+= a * b
          a2=pow(a,2)
          b2=pow(b,2)
          s1+=a2
          s2+=b2
      #    print(i,a2,b2,s1,s2)
      if np.sqrt(s1)*np.sqrt(s2)>0:
        return(sum/(np.sqrt(s1)*np.sqrt(s2)))
      else:
        return 0
 
    def __factor_matrix(self, R,theta,S, count,K, alpha, steps, beta,gamma, error_limit):
        
        # Transform regular array to numpy array
        R = np.array(R)
 
        # Generate P - N x K
        # Use random values to start. Best performance
        N = len(R)
        M = len(R[0])
        P = numpy.random.rand(N, K)
 
        # Generate Q - M x K
        # Use random values to start. Best performance
        #Q=theta
        Q = numpy.random.rand(M, K)
        Q = Q.T
        error = 0
        # iterate through max # of steps
        for step in range(steps):
 
            # iterate each cell in r
            for i in range (len(R)):
                for j in range (len(R[i])):
                    if R[i][j] > 0:                   
                        # get the eij (error) side of the equation
                        eij = R[i][j] - numpy.dot(P[i, :], Q[:, j])
                        #print(numpy.dot(P[i, :], Q[:, j]),R[i][j]) 
                        for k in range(K):
                            # (*update_rule) update pik_hat
                            P[i][k] = P[i][k] + alpha * ( 2 *eij * Q[k][j]-beta * P[i][k]) 
                            sum=0
                            
                            for l in range(3):#len(S[j])):
                              q2=S[j][l]                            
                              print(q2,i,j,k)
                              sum+=  (Q[k][j]-Q[k][q2])
 
                            
                            ga=5/(count[i])
                           # print(ga)
                            Q[k][j] = Q[k][j] + alpha * ( 2 * eij * P[i][k] - beta * Q[k][j]-ga* sum )
                            #print('after Q[k][j]=',Q[k][j])
                            #print(' Q[k][q2]]=',Q[k][q2])
                           # Q[k][j] = Q[k][j] + alpha * (  2 *eij * P[i][k]- beta * (Q[k][j])-theta[k][j] ))
                           # print(Q[k][j],"  ",theta[k][j],"  ", Q[k][j]-theta[k][j])
          
        self.Q = Q.T
        self.P = P
 
    def rmse(self,R):
        """
        A function to compute the total mean square error
        """
        xs, ys = R.nonzero()
        predicted = self.predict_all()
        count=0
        error = 0
        for x, y in zip(xs, ys):
            count=count+1
            error += pow((R[x, y] - predicted[x, y]), 2)
        return np.sqrt(error/count)
   
    
    def mae(self,R):
 
      xs, ys = R.nonzero()
      predicted = self.predict_all()
      count=0
      error = 0
      for x, y in zip(xs, ys):
 
        count=count+1
        error += abs((R[x, y] - predicted[x, y]))
      return (error/count)
    

In [ ]:
#read 1682_32 file after AE Bert 'plot_vec_AE_1682_32'
from google.colab import files
uploaded = files.upload()

Saving coun_vectorize_Genre_Title_Director_After_AE_3883_20.npy to coun_vectorize_Genre_Title_Director_After_AE_3883_20.npy


In [ ]:
#theta=np.load('plot_vec_AE_1682_20.npy',allow_pickle=True)

In [ ]:
theta=np.load('coun_vectorize_Genre_Title_Director_After_AE_3883_20.npy',allow_pickle=True)

In [ ]:
print(np.max(theta))


12.020227




```
# This is formatted as code
```

## Create Similarity Graph

In [ ]:
#crear similartity graph, 10 for each node
from scipy.spatial import distance
n,m=theta.shape
#print(n,m)
D=np.zeros((n,n))

for i in range(n):  
  for j in range(i+1,n):
          
            D[i][j] = distance.euclidean(theta[i], theta[j])
            D[j][i]=D[i][j]
#similiraty betw one item with itself
for i in range(n):
  D[i][i]=500

s = [ ]
for i in range(n):
  s.append([])
  for j in range (10):
    
    a=np.argmin(D[i])
   # print(i,a,D[i][a])
    s[i].append(a)
    #print(i,a,D[i][a])
    D[i][a] = 1000

In [ ]:
print(s[3880])

[3509, 3486, 3367, 1522, 1591, 3252, 3681, 1545, 1660, 3023]


In [ ]:
b=MF_Theta()    
b.fit(Rating,theta,s,count,latent_features_guess=20,learning_rate=0.001,steps=20,regularization_penalty=0.001)
print("all items:")

print(b.mae(Rating))
print(b.rmse(Rating))

print("cold items:")
print(b.mae(cold))
print(b.rmse(cold))
print("Heavy items:")

print(b.mae(heavy_item))
print(b.rmse(heavy_item))
print("controversial items:")

print(b.mae(contro_item))
print(b.rmse(contro_item))

training model...
3045 0 0 0
255 0 0 0
1 0 0 0
3045 0 0 1
255 0 0 1
1 0 0 1
3045 0 0 2
255 0 0 2
1 0 0 2
3045 0 0 3
255 0 0 3
1 0 0 3
3045 0 0 4
255 0 0 4
1 0 0 4
3045 0 0 5
255 0 0 5
1 0 0 5
3045 0 0 6
255 0 0 6
1 0 0 6
3045 0 0 7
255 0 0 7
1 0 0 7
3045 0 0 8
255 0 0 8
1 0 0 8
3045 0 0 9
255 0 0 9
1 0 0 9
3045 0 0 10
255 0 0 10
1 0 0 10
3045 0 0 11
255 0 0 11
1 0 0 11
3045 0 0 12
255 0 0 12
1 0 0 12
3045 0 0 13
255 0 0 13
1 0 0 13
3045 0 0 14
255 0 0 14
1 0 0 14
3045 0 0 15
255 0 0 15
1 0 0 15
3045 0 0 16
255 0 0 16
1 0 0 16
3045 0 0 17
255 0 0 17
1 0 0 17
3045 0 0 18
255 0 0 18
1 0 0 18
3045 0 0 19
255 0 0 19
1 0 0 19
3881 0 47 0


IndexError: ignored

In [ ]:
#without theta
a=MF()    
a.fit(Rating,latent_features_guess=60,learning_rate=0.01,steps=20,regularization_penalty=0.01)
print("All Data:")
print(a.mae(Rating))
print(a.rmse(Rating))

print("cold items:")
print(a.mae(cold))
print(a.rmse(cold))

print("Heavy items:")
print(a.mae(heavy_item))
print(a.rmse(heavy_item))

print("controversial items:")
print(a.mae(contro_item))
print(a.rmse(contro_item))


training model...
All Data:
0.3253984727515407
0.43343652105157493
cold items:
1.8783153576303313
1.5278109796878971
Heavy items:
1.2544429084373556
1.5641784169702573
controversial items:
1.2390938375005094
1.542049938160721


In [ ]:
print("cold ites:")
print(a.mae(cold))
print(a.rmse(cold))
print("Heavy items:")

print(a.mae(heavy_item))
print(a.rmse(heavy_item))
print("controversial items:")

print(a.mae(contro_item))
print(a.rmse(contro_item))

cold ites:
1.5435335560103252
1.8546425929856445
Heavy items:
1.1188702636948304
1.386653643823256
controversial items:
1.106969121118191
1.3664087620307814


In [ ]:
b=MF_Theta()    
b.fit(Rating,theta,s,latent_features_guess=20,learning_rate=0.0002,steps=20,regularization_penalty=0.01)
print(b.mae(Rating))
print(b.rmse(Rating))
p,q=b.get_models()

In [ ]:
print(b.mae(Rating))
#

0.7842490732990325


In [ ]:
#genre direcror title
b=MF_Theta()    
b.fit(Rating,theta,latent_features_guess=20,learning_rate=0.01,steps=10,regularization_penalty=0.01)
print(b.mae(Rating))
print(b.rmse(Rating))
p,q=b.get_models()
##print(b.mae2(Rating,theta))
#print(b.rmse2(Rating,theta))

training model...
0.5947370122601221
0.7598273314951258


In [ ]:
e=numpy.dot(p,theta)
print(np.max(e),np.min(e),np.mean(e))
e1=numpy.dot(p,q)
print(np.max(e1),np.min(e1),np.mean(e1))

9.443364524127048 0.35935008167072174 4.8432821493420155
8.052814538784524 -2.1224776980927005 3.26547624467434


In [ ]:
print(np.max(p),np.min(p),np.mean(p))
print(np.max(q),np.min(q),np.mean(q))
print(np.max(theta),np.min(theta),np.mean(theta))

2.063050648212217 -1.0733357709341813 0.300902357895181
2.2410218489788267 -1.304842035004628 0.5396303451383558
2.0 -1.0 1.2829478


In [ ]:
print(e1)

[[5.38212862 5.74411864 5.44891943 ... 4.35029142 5.18046178 4.68808106]
 [4.7444895  4.78284927 5.01182735 ... 4.40124507 4.07061991 4.16538186]
 [5.47416148 5.55444549 6.12245357 ... 5.96910661 5.65731811 5.89525181]
 ...
 [4.61874793 4.05547809 4.3655105  ... 3.94269349 4.05204172 4.9691095 ]
 [5.8971968  5.18951666 6.15845884 ... 6.30443626 4.3947539  6.11895393]
 [4.97492261 4.63672388 5.01550118 ... 4.44306958 4.72948354 4.40178153]]


In [ ]:
print(np.max(e),np.min(e),np.mean(e))
print(np.max(p),np.min(p),np.mean(p))
print(np.max(q),np.min(q),np.mean(q))

9.602332036963544 -0.30498524587520365 3.2110702530053556
1.07577813135938 -0.3461025721997949 0.3661685274778785
1.1105280952136725 -0.4323788862099896 0.4385362295781754


In [ ]:
print(theta)

[[0.9105464  0.8489275  0.8615357  ... 0.87105596 0.5250816  0.7271442 ]
 [0.91220737 0.8503121  0.86288214 ... 0.87240773 0.52560437 0.7283607 ]
 [0.91078436 0.84915143 0.86142707 ... 0.8711154  0.5249889  0.7273923 ]
 ...
 [0.9119521  0.85008013 0.86270225 ... 0.87218565 0.5255249  0.728285  ]
 [0.9102013  0.8487052  0.86097413 ... 0.8705849  0.5250197  0.7268343 ]
 [0.91056776 0.8490513  0.8618048  ... 0.87111974 0.5255505  0.7273885 ]]


In [ ]:
d=numpy.dot(p,theta)

In [ ]:
print(np.max(d),np.min(d))

9.648704589986512 0.21196903099556524


In [ ]:
oldrange=(np.max(d)-np.min(d))
newrange=4
newvalue=(((d-np.min(d))*4)/oldrange)+1
OldRange = (OldMax - OldMin)  
NewRange = (NewMax - NewMin)  
NewValue = (((OldValue - OldMin) * NewRange) / OldRange) + NewMin

In [ ]:
#a=(numpy.dot(p[12, :], q[:,0]))
f=numpy.dot(p,q)


In [ ]:
print(newvalue.shape)
print(f.shape)
print(Rating.shape)

(943, 1682)
(943, 1682)
(943, 1682)


In [ ]:
def pre(R,pred):
        
        predicted = pred
        count=0
        error = 0
        for x, y in samples:
            count=count+1
            error += pow((R[x, y] - predicted[x, y]), 2)
        return np.sqrt(error/count)

In [ ]:
print(rmse2(Rating,numpy.dot(p,q)))


0.6785660870244113


In [ ]:
print(rmse2(Rating,numpy.dot(p,q)))
print(rmse2(Rating,numpy.dot(p,theta/2)))


0.7664048211222454
1.6181296445219284


In [ ]:
print(pre(Rating,newvalue))


1.137281086094699


In [ ]:
  def rmse2(R,pred):
        """
        A function to compute the total mean square error
        """
        xs, ys = R.nonzero()
        predicted = pred
        count=0
        error = 0
        for x, y in zip(xs, ys):
            count=count+1
            error += pow((R[x, y] - predicted[x, y]), 2)
        return np.sqrt(error/count)

In [ ]:
samples=[]
for i in cold:
  j=np.nonzero(Rating[:,i])
 
  for k in j:
    for s in k:
      samples.append([s,i])
       #print((f[s,i],newvalue[s,i],Rating[s,i]))

In [ ]:
def similarity(q1,q2,R):

              
        sum=0     
        s1=0
        s2=0   
        for i in range (len(R)):         
          if ( R[i,q1]>0) and (R[i,q2]>0):
            a=R[i][q1]- np.mean(R[:,q1])
            b=R[i][q2]- np.mean(R[:,q2])
            sum+= a * b
            a2=pow(a,2)
            b2=pow(b,2)
            s1+=a2
            s2+=b2
        #    print(i,a2,b2,s1,s2)
        if np.sqrt(s1)*np.sqrt(s2)>0:
          return(sum/(np.sqrt(s1)*np.sqrt(s2)))
        else:
          return 0

In [ ]:
print(similarity(40,40,Rating))

1.0


In [ ]:
print(np.mean(Rating[1,:]))

0.1367419738406659


In [ ]:

print(np.nonzero(Rating[:,1]))

(array([  0,   4,  12,  21,  29,  41,  48,  63,  71,  82,  86,  91,  94,
       101, 109, 129, 177, 192, 196, 199, 200, 206, 212, 216, 221, 233,
       248, 249, 255, 266, 267, 270, 275, 278, 279, 291, 292, 300, 302,
       304, 319, 324, 326, 345, 362, 372, 373, 377, 378, 384, 386, 392,
       397, 398, 404, 406, 415, 424, 428, 434, 441, 449, 454, 465, 471,
       483, 486, 494, 496, 505, 520, 531, 535, 542, 550, 560, 565, 599,
       617, 620, 621, 626, 631, 639, 641, 642, 647, 649, 652, 654, 659,
       670, 681, 685, 704, 708, 714, 726, 737, 745, 748, 750, 756, 763,
       772, 773, 789, 794, 795, 797, 803, 805, 806, 814, 825, 829, 843,
       845, 863, 867, 869, 879, 885, 888, 891, 895, 898, 915, 923, 933,
       942]),)


In [ ]:
print(len(Rating[1,:]))
print(len(Rating[:,1]))

1682
943
